src/scheduler/pbsfs.c, src/server/req_stat.c, src/server/run_sched.c, src/server/sched_func.c, src/server/svr_func.c
Reduce sched_save_db calls for sched object.
fix pbsfs crash when unknown scheduler is given as parameter to the argument -I.
Solution:
1. Reduced lot of sched_save_db calls by not storing scheduler's state in to DB.
2. Scheduler now has only two states i.e. idle if scheduling is false for that scheduler or scheduling if scheduling for that scheduler is true or 1.
3. Making use of the flag  ATR_ACTION_RECOV to make sure we do not call uncessary sched_save_db calls. 
SmokeTest got passed. Also made sure that pbsfs does not crash in case of unknown scheduler.
=> Code changes to minimize sched_save_db calls

src/lib/Libdb/db_postgres_job.c, src/server/array_func.c, src/server/job_recov_db.c, src/server/svr_jobfunc.c
1. Parrent array job state was not coming as expected because PBS doesn't save the parent attributes to the db.
2. db_to_svr_job call freeing the subjob tracking table index from parent job structure during refresh_job() call.
1. Saving the parent job attributes to the db through svr_setjobstate().
2. Added a check to the setup_arrayjob_attrs
=> Fixed missing array jobs state and substate during refresh_job and added >= to the db query

src/server/req_quejob.c
Missed the array signature [ ] during jobid hashing in req_commit
Added [ ] bracket to the allocated jobid after hashing
=> Missed the array signature [ ] during jobid hashing in req_commit

src/include/reservation.h, src/lib/Libpython/pbs_python_svr_internal.c, src/server/array_func.c, src/server/job_func.c, src/server/job_recov_db.c, src/server/node_manager.c, src/server/pbsd_init.c, src/server/req_delete.c, src/server/req_manager.c, src/server/req_modify.c, src/server/req_quejob.c, src/server/req_rescq.c, src/server/req_stat.c, src/server/svr_chk_owner.c, src/server/svr_jobfunc.c, src/tools/pbs_python.c, test/tests/pbs_smoketest.py
1. Make reservation object stateless.
2. Fetch reservation queue from database.
3. Reservation refreshes with the latest records from db during pbs_rstat same as qstat.
3. No need to fetch reservation and it's associated queue from db if the caller server itself is the owner of the reservation.
4. Fixed array job preemption issue.
Smoke test results has been attached for our reference only in which all tests are passed.
[ptl_smoketest_logs.txt](https://github.com/subhasisb/pbspro/files/3477675/ptl_smoketest_logs.txt)
=> Implemented stateless reservations and fixed array job preemption issue

src/include/pbs_sched.h, src/include/server.h, src/server/pbsd_init.c, src/server/pbsd_main.c, src/server/req_manager.c, src/server/req_shutdown.c, src/server/req_stat.c, src/server/run_sched.c, src/server/sched_func.c, src/server/svr_recov.c, src/server/svr_recov_db.c
Making server object stateless.
- Making server object stateless
- Code changes to avoid duplicate rows in server table
- Adding locking during setting/unsetting server attributes
- Atomicity during server set/unsetting of attributes
- Lock sched object wherever needed(Mostly during set/unset of its attributes)
Ran smoke test. All tests are passing.
=> Making server object stateless and miscellenious changes 

src/lib/Libutil/misc_utils.c, src/server/req_quejob.c
1. get_next_hash() doesn't return proper resvid.
2. It doesn't rollback to zero after server max jobid's limit.
1. Added a pair of parenthesis where server calls get_next_hash() in req_resvSub() to get the reservation id.
2. Added +1 in max_id during rollback in get_next_hash()
=> get_next_hash() doesn't return proper resvid and also doesn't rollback to zero after max job limit

src/include/attribute.h, src/include/pbs_sched.h, src/include/server.h, src/server/pbsd_main.c, src/server/process_request.c, src/server/req_stat.c, src/server/run_sched.c, src/server/sched_func.c
Extend the framework of object recovery policy from db to Scheduler object as well. 
- Extend the framework of object recovery policy from db to Scheduler object as well. 
- Make sure that if there is any change in scheduler attributes, all other servers which cached this object also get updated as soon as possible
- In next_task we will check if it is time to call scheduler ONLY if at all if scheduling for the corresponding scheduler is true.
- Smoke Test
- Made sure that change of scheduler attributes will reflect as soon as possible at the other servers
- Made sure that whenever a scheduler transaction happens we only recover sched object from db. Verified it through gdb.
=> Object recovery policy for sched object and miscellenious bug fixes

src/server/pbsd_main.c
next_task is getting called continuously due to not calculating delay when scheduling is off.
calculate delay first and then check if scheduling is off/on and then proceed accordingly.
Verified by making scheduling off and observed that next_task is not getting called continuously.
=> Fix for next_task getting called in a loop

src/lib/Libdb/db_postgres.h, src/lib/Libdb/db_postgres_que.c, src/server/job_recov_db.c, src/server/req_stat.c
qstat -Qf command doesn't fetch newly added/modified queues from db
Now, qstat -Qf will fetch queues from db if it's not in memory or else refresh the existing queue pointer with latest data.
=> Added code to refresh/retrieve the queue from db during qstat -Qf

src/cmds/scripts/pbs_db_schema.sql, src/include/pbs_db.h, src/include/queue.h, src/lib/Libdb/db_postgres.h, src/lib/Libdb/db_postgres_common.c, src/lib/Libdb/db_postgres_que.c, src/server/queue_func.c, src/server/queue_recov_db.c, src/server/req_stat.c
1. If queue is deleted by one server then other servers also needs to delete the same queue from memory and it's related objects.
2. queue is deleted from db but still some server showing it's stats from memory
1. Added a column to the pbs.queue table named as qu_deleted.
2. Update column with value 1 upon deletion else is 0.
3. During loading the queue from db if qu_deleted value is 1 this means que has been deleted already by other servers.
4. If que hasn't refreshed since from past one day then que will have to update oneself with the latest data from db.
=> Queue synchronization and deletion between multiple servers

src/include/queue.h, src/lib/Libdb/db_postgres_que.c, src/lib/Libdb/db_postgres_resv.c, src/server/node_func.c, src/server/pbsd_main.c, src/server/req_manager.c, src/server/req_stat.c, src/server/svr_func.c
1. Need to lock the queue row during set/unset resource or attribute.
2. Need to load all the queues from db before going to perform any operation on whole list of queues.
1. Added lock during set/unset resource or attribute.
2. Added a call to get_all_db_queues() which will refresh all the queues data and also add queue if not present in memory. 
Smoke test result:  [ptl_smoke.txt](https://github.com/subhasisb/pbspro/files/3609306/ptl_smoke.txt)
=> Added locks during queue attr/resc set/unset

src/lib/Libpython/pbs_python_svr_internal.c, src/resmom/mom_hook_func.c, src/server/array_func.c, src/server/attr_recov_db.c, src/server/job_recov.c, src/server/job_recov_db.c, src/server/node_func.c, src/server/node_manager.c, src/server/pbsd_init.c, src/server/pbsd_main.c, src/server/req_delete.c, src/server/req_holdjob.c, src/server/req_jobobit.c, src/server/req_manager.c, src/server/req_movejob.c, src/server/req_quejob.c, src/server/req_register.c, src/server/req_runjob.c, src/server/req_stat.c, src/server/req_track.c, src/server/resc_attr.c, src/server/svr_func.c, src/server/svr_jobfunc.c, src/server/svr_movejob.c
1. Appended an extra flag **ATR_VFLAG_MODIFY** after **ATR_VFLAG_MODCACHE**
everywhere except **req_stat.c** file because i guess PBS never updates db through stat.
2. Removed **ATR_VFLAG_MODCACHE** check in **encode_attr_db** function so now onwards will save only those attributes which have  **ATR_VFLAG_MODIFY** flag enabled.
=> Appended an extra flag named as ATR_VFLAG_MODIFY

src/cmds/scripts/pbs_db_schema.sql, src/include/pbs_db.h, src/include/pbs_nodes.h, src/include/queue.h, src/lib/Libdb/db_postgres.h, src/lib/Libdb/db_postgres_impl.c, src/lib/Libdb/db_postgres_node.c, src/lib/Libdb/db_postgres_nodejob.c, src/server/node_func.c, src/server/node_recov_db.c, src/server/queue_func.c, src/server/queue_recov_db.c, src/server/req_manager.c, src/server/req_stat.c
As nodes are treated as a common object, another server should know if the node is deleted so that it can invalidate its cache. For that the nodes are marked as deleted in the DB so that other servers can fetch and invalidate its cache whenever a query is made. We also delete these nodes which are marked for deletion after T amount of time (24 hours now)
Future work:
Unlike queues, we dont have to load nodes in regular interval. That means there can be a server which does not have loaded a node during the last 24 hours during which it got deleted. This case needs to be addressed. 
This can be as simple as, during T/2 hours (where T is the time interval where object will get deleted from DB) every server should try to make sure nodes in its cache are not marked for deletion.
=> node object deletion with multi server

src/include/libpbs.h, src/include/libutil.h, src/include/pbs_ifl.h, src/lib/Libifl/pbsD_connect.c, src/lib/Libutil/misc_utils.c, src/resmom/catch_child.c, src/resmom/mom_comm.c, src/resmom/mom_main.c, src/resmom/mom_server.c
Describe Bug or Feature
•	The current pbs_mom would always connect to default pbs_server(port 15001).
•	This default configuration won't support for multi-server setup with non-default ports.
•	To avoid oversubscribing the same service, now pbs_mom would connect to random service(using the get_svr_shard_connection() api for that)
Describe Your Changes
•	Added new api named get_server_stream() to get the stream to connect the random server, this api would initialize the connection table to multiple-servers.
•	Modified the existing api get_svr_shard_connection() to use rpp_open() instead of internal_tcp_connect() using the respective function pointer “internal_connect()”
•	JOB updates would be sent to respective using the same get_server_stream() with jobid parameter as hint to find its …
=> POC for making mom to connect multi-server

src/include/pbs_db.h, src/include/queue.h, src/lib/Libdb/db_postgres.h, src/lib/Libdb/db_postgres_impl.c, src/lib/Libdb/db_postgres_job.c, src/lib/Libdb/db_postgres_node.c, src/lib/Libdb/db_postgres_nodejob.c, src/lib/Libdb/db_postgres_que.c, src/lib/Libdb/db_postgres_resv.c, src/lib/Libdb/db_postgres_sched.c, src/server/job_func.c, src/server/job_recov_db.c, src/server/node_recov_db.c, src/server/pbsd_init.c, src/server/pbsd_main.c, src/server/queue_func.c, src/server/queue_recov_db.c, src/server/req_manager.c, src/server/req_stat.c, src/server/sched_func.c
1. Server flag attribute was commented earlier due to value discrepancy during load from db is fixed now.
2. Added a timed task to delete all the queues(normal or resv) from the db and task will run after every 30 min as of now (we can change it later as per the requirements)
3. Fixed a bug in get_all_db_queues() in which if last que is marked as deleted in db then every time it was fetching all the queues instead of delta records.
4. Added a time interval of 30 secs in pbsd_main during get_all_db_queues() call.
[ptl_smoketest.txt](https://github.com/subhasisb/pbspro/files/3742364/ptl_smoketest.txt)
=> Added work task to delete objects from db and fixed some bugs

src/lib/Libattr/master_svr_attr_def.xml, src/server/svr_func.c
As the sched_formula file was deleted from server_priv after the job_sort_formula was loaded to memory. We were not able to decode the formula next time when it is saved in db and loaded to memory.
As a quick fix decode_str was used.  After analysing the issue found out that decode_formula was itself deleting the file after loading. That step is removed and decode_formula is used.
=> Job_sort_formula validation fixed

src/include/libpbs.h, src/lib/Libifl/pbsD_connect.c, src/lib/Libutil/misc_utils.c, src/resmom/catch_child.c, src/resmom/mom_main.c, src/scheduler/pbs_sched.c
* Fixes the issue related to initial connection failure for node updates. (Intermitted issues) 
* Fix for making the MoM to send hellosvr, if the first connection goes down.
* Modified the get_svr_shard_connection() API for below 2 purposes. 
1) If the Mom to server connection not exists, it connects via rpp_open and returns stream descriptor.
2)If the connection already exists, it returns the already connected stream descriptor.
=> fix for MoM connection to another server, if first server goes down

src/lib/Libutil/misc_utils.c
* Adding more granular in time from sec to micro-sec, while setting seed for the random generator.
* Tested the changes in blrentperf03 machine and observed 21 moms -> server connection was distributed across all servers.
[21_moms_connection_distributed_across_all_servers.txt](https://github.com/subhasisb/pbspro/files/3919150/21_moms_connection_distributed_across_all_servers.txt)
=> Changing the random seed time from sec to microsec

src/include/libutil.h, src/include/log.h, src/include/mom_func.h, src/include/net_connect.h, src/include/pbs_nodes.h, src/lib/Libattr/attr_node_func.c, src/lib/Libifl/int_submit.c, src/lib/Libifl/xml_encode_decode.c, src/lib/Libtpp/tpp_util.c, src/lib/Libutil/misc_utils.c, src/resmom/catch_child.c, src/resmom/mom_main.c, src/resmom/mom_server.c, src/resmom/start_exec.c, src/resmom_win/start_exec.c, src/server/issue_request.c, src/server/mom_info.c, src/server/node_func.c, src/server/node_manager.c, src/server/pbsd_main.c, src/server/process_request.c, src/server/req_manager.c, src/server/svr_connect.c, src/server/svr_func.c, test/fw/ptl/lib/pbs_testlib.py, test/tests/functional/pbs_job_array.py
Overview
There is a sequence of dialogue taking place between the server and mom when they come up. This change focuses on reversing the initial exchange to reduce the overhead on the server and making it adaptable for future scalability enhancements.
Initial Dialogue Exchange:
Initial dialogues exchange is a number of message exchange happens between server and mom before the server shows the node as up. The number of message exchange is reduced. Following is a sequence diagram of how mom-server interaction appeared before and now.
IS_HELLOSVR
When the server comes up it sends IS_HELLO to all the moms in the cluster. Mom will reply back with a list of jobs and state information. This is not an efficient method as the server has to deal diligently to keep track of the moms who have not …
=> Mom will initiate the dialogue sequence with server

src/include/pbs_error.h, src/lib/Libifl/pbsD_termin.c, src/server/pbsd_main.c
* Qterm is crashing, the actual issue is when the first server goes down, it kills the Postgres server too. Thus causing the subsequent server termination failure.
* PBS errno was not right.
* Adding a condition for stopping DB server only single-server mode, allowing to run for multi-server mode, so that other servers could access the Postgres.
* Updating correct PBS errno.
Testing logs with multiple servers:
[Quickfix_qterm_crash.txt](https://github.com/subhasisb/pbspro/files/4534405/Quickfix_qterm_crash.txt)
=> Bugfix for qterm crash and correcting errno

src/cmds/scripts/pbs_dataservice, src/cmds/scripts/pbs_habitat.in, src/cmds/scripts/pbs_init.d.in, src/server/pbsd_main.c
Currently, the PBS init script doesn't support the start/stop/status of multiple servers.
Changed init script and its dependent scripts to start/stop/status of multiple servers
(Assumption, all servers configured in PBS_SERVER_INSTANCES are assumed for local host, as we don't have support for multi-host multi-server support yet, once we have that, we have to change these scripts again)
None
[after.txt](https://github.com/subhasisb/pbspro/files/4563567/after.txt)
=> Multiserver support in pbs_init.d

src/include/pbs_ifl.h, src/include/pbs_internal.h, src/lib/Libifl/int_hook.c, src/lib/Libifl/int_jcred.c, src/lib/Libifl/int_manage2.c, src/lib/Libifl/int_msg2.c, src/lib/Libifl/int_rdrpy.c, src/lib/Libifl/int_sig2.c, src/lib/Libifl/int_status2.c, src/lib/Libifl/int_submit.c, src/lib/Libifl/int_submit_resv.c, src/lib/Libifl/int_ucred.c, src/lib/Libifl/pbsD_asyrun.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_defschreply.c, src/lib/Libifl/pbsD_locjob.c, src/lib/Libifl/pbsD_movejob.c, src/lib/Libifl/pbsD_msgjob.c, src/lib/Libifl/pbsD_orderjo.c, src/lib/Libifl/pbsD_rerunjo.c, src/lib/Libifl/pbsD_resc.c, src/lib/Libifl/pbsD_runjob.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libifl/pbsD_stagein.c, src/lib/Libshard/shard_functions.c, src/lib/Libutil/misc_utils.c, src/resmom/catch_child.c, src/resmom/mom_comm.c, src/resmom/mom_main.c, src/resmom/mom_server.c
Describe Bug or Feature
To avoid the oversubscription of the default server, now pbs_mom would connect to any one of the random server (using the get_svr_shard_connection()).
Describe Your Changes
Added new api named get_server_stream() to get the stream to connect the random server, this api would initialize the shard connection table to multiple-servers.
If the initially connected server goes down, PBS_MOM would connect to the next available server for node info updates.
JOB updates would be sent to respective using the same get_server_stream() with the jobid as a hint to find its server.
Added another API set_server_stream(), that helps to update the shard connection table to preserve the new incoming connection from the new stream descriptor to the server index appropriately.
Updated …
=> Making PBS_MOM to work with multi-servers (PR 3)

src/server/pbsd_init.c, src/server/req_quejob.c, test/tests/functional/pbs_trillion_jobid.py
The Jobid sequences for multiple servers are not generating in proper order. 
Changed the get_next_svr_sequence_id() function for proper seq generation by refering the libshard api.
[Job_id_seq_test_logs.txt](https://github.com/subhasisb/openpbs/files/4679476/Job_id_seq_test_logs.txt)
TH3 results: No test failure for Jobid
=> Job id fix for multi-server mode

src/include/pbs_ifl.h, src/include/server.h, src/lib/Libattr/master_svr_attr_def.xml, src/server/req_select.c, src/server/req_stat.c
Adds a new server attribute called "job_stat_limit". By default it's set to 0 to allow normal sites to operate as is. For HTC sites, this should be set accordingly. I think we need to be careful in what number we recommend. If we recommend a smaller number, the scheduler will just take much longer to process the same number of jobs as it would have in a single stat of all jobs. I'd personally recommend setting this number to 100,000/number of servers.
Added a new server attribute, which when set makes it limit the number of jobs sent to scheduler in one cycle.
=> Throttle jobs to sched

src/include/libpbs.h, src/include/pbs_internal.h, src/include/sched_cmds.h, src/scheduler/get_4byte.c, src/scheduler/globals.c, src/scheduler/globals.h, src/scheduler/pbs_sched.c, src/server/pbsd_main.c, src/server/run_sched.c
Introduce a new scheduling command SCH_SVR_ID to pass "pbs_server_name:port" to Scheduler as soon as the connection establishes.
host_name of svr_conns table (of type svr_conn_t) is populated as follows in side the scheduler.
```
if ((phe = gethostbyaddr((char *) &saddr_in.sin_addr, sizeof(saddr_in.sin_addr), AF_INET)) == NULL)  
return -1;
strcpy(svr_conns[svr_id]->host_name, phe->h_name);
```
This host_name for all the svr_conns instances remains same if we have n number of different PBS complexes set up in single machine where in we have aliases for the pbs conf parameter PBS_SERVER. 
In order to get the actual pbs_server name and port we introduced the above new scheduling command through which we pass "pbs_server_name:port" which can be stored inside svr_conns table.
Also this …
=> Introducing new sched command SCH_SVR_ID 

src/cmds/scripts/install_db, src/cmds/scripts/pbs_dataservice, src/cmds/scripts/pbs_habitat.in, src/cmds/scripts/pbs_init.d.in
* When no PBS instance is running update_pids/getpid in pbs_init.d will set -1 as PID of all daemons, and newly added hup_pbs code runs kill -HUP on it without checking it
* Make sure daemons PID is not -1 and it is up and running before running kill -HUP on it
* None
[log.txt](https://github.com/subhasisb/openpbs/files/4867634/log.txt)
=> Fix pbs_add_server when no pbs instance is running

src/scheduler/fifo.c, src/scheduler/globals.c, src/scheduler/globals.h, src/scheduler/pbs_sched.c
This PR addresses the following.
- Some of the stats failing from sched when it is started first before Server in Multi-Server environment
- Fix for race conditions in Scheduler's secondary connections.
- This PR handles race conditions when lot of failures happen at the Scheduler which could be because of stats failing from scheduler or any other reason. 
Attached are test logs.
[PR108.logs.txt](https://github.com/subhasisb/openpbs/files/4930214/PR108.logs.txt)
=> Code fix for stat issues when sched starts first in Mulit-Server environment

src/scheduler/fifo.c, src/scheduler/globals.c, src/scheduler/globals.h, src/scheduler/pbs_sched.c
- When new servers in different PBS complex or in the same host are added while the Scheduler is running, Scheduling is not happening properly.
- pbs_statsched is failing which triggers Scheduler to not function properly
- When new servers in different PBS complex or in the same host are added while the Scheduler is running, Scheduling is not happening properly..
**Root cause:** While adding new servers either manually or through pbs_add_server script, pbs_conf is updated to have the new server details(hostname and port) to PBS_SERVER_INSTANCES which triggers SIGHUP upon which Scheduler reloads pbs_conf and sched_config. During this time we might need to update scheduler's connection array data structure to have a room for more servers and allocate memory and initialise accordingly  and …
=> Scheduling is not working when new servers added while scheduler is running

src/cmds/scripts/pbs_pocker
* client commands gives auth error when run as non-root user due to missing SUID bit on pbs_iff
* added needed command to set SUID bit on pbs_iff and pbs_rcp after make install
* None
=> Fix auth error in cluster created by pocker

src/scheduler/fifo.c, src/scheduler/pbs_sched.c, src/server/pbsd_main.c, src/server/req_shutdown.c, src/server/run_sched.c
This PR consists of the following changes 
- Changes needed to send sched commands on secondary connection. For more details please refer PR #118. 
- Added code changes for few more race conditions apart from the above and also fixed few more bugs like the below ones.
- Now that we are passing sched commands on secondary connection, necessary changes needed to close_server_conn() like clearing the secondary connection from fd_set.
- We should not directly assign -1 to server connections within sched code. If we do this, there is no notification sent to Server which can cause more problems. Removed this part of the code and made sure the scenario "Stop server, Bring it back while sched is running" works. Also tried various other things like restart complex1 when complex2 is up and vice …
=> Server sending sched commands on secondary + Bug fixes for few more race conditions

src/include/libpbs.h, src/include/pbs_ifl.h, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libutil/misc_utils.c, src/scheduler/job_info.c, src/scheduler/node_info.c, src/scheduler/pbs_sched.c
As of now get_svr_index() is being used inside Scheduler code heavily especially under the following scenarios.
- For every job 
- For every node
This happens for every cycle when we query the data from Server/s. get_svr_index() loops through all svr_conns given a server name to find out the index associated with that server. Looping svr_conns array for every job and node is very costly and is O(n) time complexity where n is proportional to number of servers. The function also does a strcmp to match the server name with the given name which is again a costly operation. This enhancement is an attempt to not use get_svr_index() in the above situations and makes Scheduler to get server index in O(1) time in the above scenarios. 
In fact Scheduler now uses get_svr_index() only once when …
=> scheduler performance improvement for get_svr_index

src/cmds/Makefile.am, src/include/libpbs.h, src/include/pbs_ifl.h, src/lib/Libdis/dis_helpers.c, src/lib/Libifl/dec_attrl.c, src/lib/Libifl/dec_rpyc.c, src/lib/Libifl/enc_reply.c, src/lib/Libifl/int_rdrpy.c, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_selectj.c, src/scheduler/data_types.h, src/scheduler/job_info.c, src/scheduler/misc.c, src/scheduler/misc.h, src/scheduler/node_info.c, src/scheduler/server_info.c, src/server/dis_read.c, src/server/hook_func.c, src/server/pbsd_init.c, src/server/pbsd_main.c, src/server/reply_send.c, src/server/req_message.c, src/server/req_select.c, src/server/req_stat.c, src/server/stat_job.c, src/tools/Makefile.am, valgrind.supp
* Cherry-pick stat fix new changes and svr shutdown optimization from master
* Optimized setting svr_index on each job/node in sched
* For optimization svr_index, simply set my_index on sinfo after query_server based on socket used in IFL (and for this we only loop through svr_conns array 1 time per server and compare pbs_sd with svr_conn_t->sd), then in query job/node, assign sinfo->my_index to job/node->svr_index
* None
* coming soon
=> Cherry-pick stat fix and svr shudown optimization from master

src/scheduler/misc.c
pbs_sched does not come up if fqdn is used in PBS_SERVER_INSTANCES and short hostname is used in PBS_SERVER and vice versa in the pbs.conf file.
If Server connects to Scheduler, the server index is calculated using the function get_svr_index(). In this function we compare the given server name with PBS_SERVER. If one of them is fqdn and the other is short hostname the check fails and this function returns -1 as server index. So sched complains "Unknown Server" and does not come up.
Solution is always compare short hostname of the server if fqdn/short hostname are mixed in the above conf variables, If not do a full compare.
Attached are the UNIT testing logs.
[fqdn_issue.txt](https://github.com/subhasisb/openpbs/files/5067472/fqdn_issue.txt)
=> pbs_sched does not come up if fqdn and short hostname are mixed in conf file

src/include/libutil.h, src/lib/Libifl/pbs_loadconf.c, src/lib/Libutil/misc_utils.c, src/scheduler/pbs_sched.c
* parse_psi doesn't honour PBS_BATCH_SERVICE_PORT in pbs.conf
* call parse_psi after parsing whole pbs.conf and use pbs_conf.batch_service_port as default port
* None
[before.txt](https://github.com/subhasisb/openpbs/files/5067460/before.txt)
[after.txt](https://github.com/subhasisb/openpbs/files/5067458/after.txt)
=> Fix parse_psi

src/scheduler/misc.c, src/scheduler/misc.h, src/scheduler/pbs_sched.c
Scheduler goes to infinite loop for the following Admin configuration/scenario.
**Configuration :** Multiple Servers with the same server name but with different port numbers configured in PBS_SERER_INSTANCES
Found some other valid configurations for which the above issue can happen. For example
- Unknown Server which is not part of PBS_SERVER_INSTANCES connecting to pbs_sched. Scheduler should not go down in this case.
- Multiple Servers with the same port but one server name is a substring of another server name
- FQDN in PBS_SERVER_INSTANCES but short server name in PBS_SERVER
- Short server name in PBS_SERVER_INSTANCES but fqdn in PBS_SERVER
- Duplicate entry in PBS_SERVER_INSTANCES
- Multiple Servers with the same port but one server name is a substring of another server name. Here …
=> Scheduler bug fixes to handle various Admin configurations for Multi-Server

src/include/libauth.h, src/include/libpbs.h, src/include/libutil.h, src/include/net_connect.h, src/include/pbs_nodes.h, src/include/server.h, src/lib/Libifl/int_status.c, src/lib/Libifl/int_submit.c, src/lib/Libnet/net_server.c, src/lib/Libutil/misc_utils.c, src/resmom/mom_server.c, src/server/Makefile.am, src/server/mom_info.c, src/server/multi_svr.c, src/server/node_func.c, src/server/node_manager.c, src/server/pbsd_main.c, src/server/process_request.c, src/server/req_manager.c, src/server/req_movejob.c, src/server/req_quejob.c, src/server/req_runjob.c, src/server/svr_connect.c, src/server/svr_movejob.c
* Using TPP for inter-server job transfer in case of multi-server.
* Failures in move + run path, job seems stuck in T state, Protocol error in server logs
Why? As multiple forked processes trying to read the reply from peer server using the same FD, they might be reading the wrong values.
Fix: Commenting out the code for reusing FD. This will be cleaned up when we make use of send_job_exec path.
* Resources Aggregation garbles values and qstat -Bf intermittent failures
Testing:
[accounting_records_1000_jobs.txt](https://github.com/subhasisb/openpbs/files/5070702/accounting_records_1000_jobs.txt)
=> Using TPP for inter-server communication

src/cmds/scripts/pbs_dataservice, src/lib/Libnet/net_client.c, src/lib/Libtpp/tpp_router.c, src/lib/Libtpp/tpp_transport.c, src/resmom/mom_main.c, src/scheduler/pbs_sched.c, src/server/process_request.c, test-scripts/build-image.sh, test-scripts/config.json, test-scripts/entrypoint, test-scripts/master.py, test-scripts/readme.txt, test-scripts/run-test.sh, test-scripts/submit-jobs.sh
* Disable/remove code to authenticate using resvport to allow to run PBS in non-priv containers
* Ignore setting limits to allow to run mom in non-priv containers
* Add test scripts (just for safe keeping)
[master.log](https://github.com/subhasisb/openpbs/files/5174818/master.log)
=> Disable resvport authentication for non-priv containers and safe keeping test scripts

src/lib/Libifl/pbs_loadconf.c, src/scheduler/check.c, src/server/multi_svr.c
Scheduler crashes when a single or a set of servers do not have any nodes. Following is the backtrace.
```
(gdb) bt
#0  on_segv (sig=0) at pbs_sched.c:172
#1  <signal handler called>
#2  0x0000000000471bee in check_normal_node_path (policy=0xd4f4b0, sinfo=0xd185c0, 
qinfo=0xcc2460, resresv=0x7f49f8001910, flags=0, err=0xd4e8e0) at check.c:1622
#3  0x000000000047183a in check_nodes (policy=0xd4f4b0, sinfo=0xd185c0, qinfo=0xcc2460, 
resresv=0x7f49f8001910, flags=0, err=0xd4e8e0) at check.c:1486
#4  0x0000000000470d66 in is_ok_to_run (policy=0xd4f4b0, sinfo=0xd185c0, 
qinfo=0xcc2460, resresv=0x7f49f8001910, flags=0, perr=0xd4e8e0) at check.c:1074
#5  0x00000000004202dd in main_sched_loop (policy=0xd4f4b0, sd=10, sinfo=0xd185c0, 
rerr=0x7fff07ee8898) at fifo.c:897
#6  0x000000000041ff49 in …
```
=> Code changes for Scheduler crash when a server/s has no nodes  + Move job issues

src/scheduler/check.c, src/scheduler/data_types.h, src/scheduler/fifo.c, src/scheduler/resource_resv.c
This is to implement the sched side changes needed to handle the race conditions around non-local and multi-node split jobs. With this, such jobs will be run with PBS_BATCH_AsyrunJob_ack (97) batch request, instead of PBS_BATCH_AsyrunJob (23).
I tested single node jobs which need to be run on a different server, the sched successfully submtited type 97 request instead of type 23 for such jobs. But I couldn't test multi-node jobs which need to be split since, I think, we don't support that yet.
=> Sched will do sync job run for non-local jobs

src/cmds/qmgr.c, src/cmds/qstat.c, src/include/pbs_ecl.h, src/include/pbs_ifl.h, src/lib/Libecl/ecl_verify_object_name.c, src/lib/Libifl/int_manager.c, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libifl/pbsD_statsched.c, src/scheduler/fifo.c, src/scheduler/fifo.h, src/scheduler/job_info.c, src/scheduler/node_info.c, src/scheduler/pbs_sched.c, src/scheduler/resv_info.c, src/scheduler/server_info.c, src/server/pbsd_main.c, src/server/req_stat.c, src/server/sched_func.c
This PR consists of the following enhancements.
- qmgr/pbs_manager request should go to all servers automatically.
- Even if one of the configured servers is not available qmgr update should fail. But the stats queries should be successful when queried through external clients. But when they are called from scheduler the operation should fail.
- Server should stop contacting Scheduler when scheduling is off. This helps in not logging the following message to server logs continuously thus by filling up all the system when scheduler is gone down.
08/25/2020 08:16:29;0001;Server@spark1;Svr;Server@spark1;Operation now in progress (115) in 
contact_sched, Could not contact Scheduler
08/25/2020 08:16:29;0001;Server@spark1;Svr;Server@spark1;Operation now in progress (115) in 
contact_sched, …
=> Schedule when all servers are ready + single mgr command for all servers + misc enhancements

src/scheduler/node_info.c, src/server/svr_chk_owner.c, test-scripts/entrypoint, test-scripts/master.py, test-scripts/run-test.sh
* qmgr fails with 15007 (PBSE_PERM) error when server is on another host, because server by default consider root on localhost/server_host as privileged, but in case of multiple servers, all servers should consider all servers host's root user as priv user 
* sched doesn't schedule any jobs if one of the servers doesn't have any nodes due to pbs_statvnodes fails with PBSE_NONODES
* Fixed permission error by validating host against all server's host if req user is root
* Ignore PBSE_NONODES in query_nodes() in sched
* Modified test-scripts to make use of qmgr broadcast instead going to each server and changing scheduling value
* None
[master.log](https://github.com/subhasisb/openpbs/files/5207748/master.log)
=> Fix for permission error on qmgr broadcast to all servers

src/include/batch_request.h, src/include/libpbs.h, src/include/libutil.h, src/include/pbs_nodes.h, src/include/server.h, src/lib/Libattr/attr_node_func.c, src/lib/Libutil/misc_utils.c, src/resmom/mom_comm.c, src/resmom/start_exec.c, src/server/dis_read.c, src/server/mom_info.c, src/server/multi_svr.c, src/server/node_func.c, src/server/node_manager.c, src/server/process_request.c, src/server/svr_func.c
Approach #2 on multi-nodes:
Node structures are created selectively on servers. When a server receives a exec_vnode to process and it could not find  that node associated with its cluster, this request is broadcasted. The receiving servers will act on the request and update the resources assigned, jobs and node state accordingly.
Note: Inter-mom communication authentication using clusteraddr2 is disabled to make testing easier. This has to be used in a trusted cluster.
=> multi-node using broadcasting resc update

src/scheduler/pbs_sched.c
When a server goes down scheduler detects it and stops scheduling. But at times it queries server universe unnecessarily and comes to know the fact that one of the server is down. If we can detect the server going down early which allows us to not to query server when there is no need. Of course this is not possible all the times. But whenever we detect it early we stop querying server universe. This avoids burden on server/s.
This also helps in avoiding 15034 errors when servers are coming up one after the other.
**sched_logs snippet**
09/24/2020 05:40:46;0080;pbs_sched;Req;;Updating scheduler attributes
09/24/2020 05:40:46;0080;pbs_sched;Req;;Starting Scheduling Cycle
09/24/2020 05:40:46;0040;pbs_sched;Resv;resv_info;pbs_statresv failed:  (15034)
09/24/2020 …
=> Bug fix for avoiding scheduler querying server universe in a corner case
