subhasisb/openpbs

src/server/process_request.c, src/server/req_quejob.c
Fix memcache_good return values 
Add find_queuebyname() to avoid loading queues later
=> Job sharding

src/scheduler/pbsfs.c, src/server/req_stat.c, src/server/run_sched.c, src/server/sched_func.c, src/server/svr_func.c
Minimize recov_sched_from_db() calls to get the better performance.
Ran all SmokeTest and all tests passed.
=> Minimize recov_sched_from_db() calls to get the better performance

src/include/libutil.h, src/include/pbs_internal.h, src/lib/Libifl/pbs_loadconf.c, src/lib/Libutil/misc_utils.c, src/server/pbsd_init.c, src/server/req_quejob.c
Added the pbs_conf variables to running multi-server
=> Add the pbs.conf variables for multiple servers

src/server/req_holdjob.c, src/server/req_quejob.c, src/server/svr_jobfunc.c, test/tests/pbs_smoketest.py
Job states and hold types were not set.
Did a full save in job state change and hold types set and unskipped 3 tests.
=> Full save for Job states and hold types.

src/cmds/qstat.c, src/cmds/qterm.c, src/cmds/scripts/pbs_init.d.in, src/include/libpbs.h, src/include/libutil.h, src/include/pbs_internal.h, src/lib/Libifl/int_manage2.c, src/lib/Libifl/int_manager.c, src/lib/Libifl/int_rdrpy.c, src/lib/Libifl/int_sig2.c, src/lib/Libifl/int_status.c, src/lib/Libifl/int_status2.c, src/lib/Libifl/int_submit.c, src/lib/Libifl/int_submit_resv.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_locjob.c, src/lib/Libifl/pbsD_movejob.c, src/lib/Libifl/pbsD_msgjob.c, src/lib/Libifl/pbsD_orderjo.c, src/lib/Libifl/pbsD_rerunjo.c, src/lib/Libifl/pbsD_runjob.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libifl/pbsD_sigjob.c, src/lib/Libifl/pbsD_submit.c, src/lib/Libifl/pbsD_termin.c, src/lib/Libifl/pbs_loadconf.c, src/lib/Libnet/net_client.c, src/lib/Libutil/misc_utils.c, src/server/req_quejob.c
PBS IFL API now handles multiple server instances transparently!
=> PBS IFL API now handles multiple server instances transparently!

src/cmds/Makefile.am, src/cmds/qsub.c, src/lib/Libdb/db_postgres_job.c, src/lib/Libdb/db_postgres_que.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/tcp_dis.c, src/lib/Libutil/misc_utils.c, src/server/pbsd_init.c, src/server/pbsd_main.c, src/server/req_quejob.c, src/server/svr_recov_db.c
Fix some sharding logic in pbsd_connect
Fix last job id calculation at server restart
=> Fix last jobid calculation at restart and some sharding logic

src/include/libpbs.h, src/include/log.h, src/include/net_connect.h, src/include/pbs_nodes.h, src/lib/Libattr/attr_node_func.c, src/lib/Libifl/int_submit.c, src/resmom/catch_child.c, src/resmom/mom_main.c, src/resmom/mom_server.c, src/scheduler/pbs_sched.c, src/scheduler/pbs_sched_win.c, src/server/dis_read.c, src/server/mom_info.c, src/server/node_func.c, src/server/node_manager.c, src/server/pbsd_main.c, src/server/process_request.c, src/server/req_manager.c, test/tests/pbs_smoketest.py
Reversal of pinging. Now on, mom will start pinging server and connect to it.
=> pinging from mom

src/cmds/multisvr, src/cmds/qsub.c, src/cmds/qsub_multi.sh, src/include/libpbs.h, src/include/reservation.h, src/lib/Libattr/master_resc_def_all.xml, src/lib/Libattr/master_svr_attr_def.xml, src/lib/Libdb/db_postgres_svr.c, src/lib/Libifl/int_submit.c, src/lib/Libifl/pbsD_submit.c, src/send_job_win/w32_send_job.c, src/server/attr_recov_db.c, src/server/job_recov_db.c, src/server/mom_info.c, src/server/node_func.c, src/server/pbsd_main.c, src/server/queue_recov_db.c, src/server/req_quejob.c, src/server/req_stat.c, src/server/run_sched.c, src/server/svr_movejob.c, src/server/svr_recov_db.c
Fix savetm returns from delete attriute operations, qsub_multi, multisvr, script save optional
=> Fix savetm returns from delete attriute operations, qsub_multi, multisvr, script save opt

src/lib/Libdb/db_postgres.h, src/lib/Libdb/db_postgres_que.c, src/lib/Libdb/db_postgres_resv.c, src/server/job_recov_db.c, src/server/req_stat.c
1. Refactored refresh_resv() and get_all_db_esvs() code
2. Added a delta query for the reservations during pbs_rstat
=> Refactored refresh resv code during pbs_rstat

src/server/job_recov_db.c, src/server/req_manager.c, src/server/req_select.c, src/server/req_stat.c
=> Make qselect to query jobs from db same as other objects

src/include/pbs_nodes.h, src/include/svrfunc.h, src/lib/Libattr/attr_node_func.c, src/lib/Libdb/db_postgres_attr.c, src/lib/Libdb/db_postgres_impl.c, src/lib/Libdb/db_postgres_node.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbs_loadconf.c, src/lib/Libpython/pbs_python_svr_internal.c, src/lib/Libutil/misc_utils.c, src/resmom/catch_child.c, src/server/hook_func.c, src/server/job_func.c, src/server/mom_info.c, src/server/node_func.c, src/server/node_manager.c, src/server/node_recov_db.c, src/server/nodejob_recov_db.c, src/server/pbsd_init.c, src/server/req_jobobit.c, src/server/req_manager.c, src/server/req_runjob.c, src/server/svr_connect.c, src/server/svr_jobfunc.c, src/server/svr_movejob.c
* Node write is optimized based on MODIFY flag
* Node state was showing BUSY after a restart
=> Node write optimization and bug fixes

src/cmds/multimom, src/cmds/multisvr, src/lib/Libattr/attr_fn_resc.c, src/lib/Libattr/master_queue_attr_def.xml, src/lib/Libdb/db_postgres_node.c, src/lib/Libifl/pbsD_submit.c, src/server/mom_info.c, src/server/node_func.c, src/server/node_manager.c, src/server/node_recov_db.c, src/server/req_manager.c
multimom script can be used the same way as the multisvr script.
`multimom $no_of_moms $start_port`
=> multi mom script and bug fixes

src/lib/Libdb/pgsql/db_resv.c, src/lib/Libdb/pgsql/pbs_db_utility
Github rebase could not get all changes because of file renames and removals.
Manually moved schema changes to db utility file.
=> Fixed rebase issues

src/lib/Libdb/pgsql/db_common.c, src/scheduler/pbs_sched.c, src/server/pbsd_main.c
Jenkins build fails on certain platforms because of signature mismatch in pbs_sched.c
Correct the signature.
=> Fix for compilation errors on SLES and RHEL8

src/cmds/scripts/Makefile.am, src/cmds/scripts/pbs_add_msvr_inst, src/cmds/scripts/pbs_add_server, src/cmds/scripts/pbs_init.d.in, src/resmom/mom_main.c, src/scheduler/pbs_sched.c, src/server/pbsd_init.c
* Add simple script to create another server instance
* Added script
* None
[log.txt](https://github.com/subhasisb/openpbs/files/4830533/log.txt)
=> Add simple script to create another server instance

src/cmds/pbsnodes.c, src/cmds/qmgr.c, src/cmds/qselect.c, src/cmds/qstat.c, src/include/libpbs.h, src/include/pbs_ifl.h, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libifl/pbsD_stathook.c, src/lib/Libifl/pbsD_statjob.c, src/lib/Libifl/pbsD_statnode.c, src/lib/Libifl/pbsD_statque.c, src/lib/Libifl/pbsD_statresv.c, src/lib/Libifl/pbsD_statrsc.c, src/lib/Libifl/pbsD_statsched.c, src/lib/Libifl/pbsD_statsrv.c, src/lib/Libutil/misc_utils.c
Old PR Link: https://github.com/subhasisb/openpbs/pull/96
=> First phase of IFL changes

src/cmds/scripts/pbs_pocker
* Add script to launch multi-server clusters in containers
* Add script to launch multi-server clusters in containers
* None
* [test.txt](https://github.com/subhasisb/openpbs/files/4925287/test.txt)
=> Add pbs_pocker

src/cmds/scripts/pbs_pocker
* Add vnode support in pbs_pocker
* Added examples
* Fixed issue for recreating image on source change
=> Add vnode support in pbs_pocker

src/cmds/qstat.c, src/include/attribute.h, src/include/batch_request.h, src/include/libutil.h, src/include/server_limits.h, src/lib/Libattr/attr_fn_size.c, src/lib/Libifl/dec_MoveJob.c, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_connect.c, src/lib/Libifl/pbsD_statque.c, src/lib/Libifl/pbsD_statsrv.c, src/lib/Libpython/pbs_python_svr_size_type.c, src/lib/Libutil/misc_utils.c, src/server/reply_send.c, src/server/req_runjob.c, src/server/svr_movejob.c
* qsub should make use of microsecond seed for randomness
* server should not acknowledge sched after async run job
* Source server should purge job if it is getting job already exists error while move and run.
* job count aggregation
* resources assigned aggregation
=> aggregation logic and other bug fixes

src/server/node_manager.c
On every invocation of free_nodes(), especially each job exit, it is consuming more time for releasing the nodes associated with the job object.
Optimized in a way that instead of looping through to "each subnode" in "each node" in "each mom", identified the exact node directly from chunks and releasing nodes using deallocate_job_from_node() function.
Test setup:
Install pbs
kill running mom kill -9 $(pidof pbs_mom)
run pbs_mom -m as root to start mock mom
pbs_config --vnodify -N 50 -a resources_available.ncpus=1000 
Run 50 moms having natual vnodes and with unique port.
turn off scheduling qmgr -c "s s scheduling=0"
submit 50k jobs (for i in $(seq 1 1 50000); do qsub -koe -- /bin/date; done; as pbsroot user)
start only one sched cycle (qmgr -c "s s scheduling=1" && qmgr -c "s s …
=> free_nodes optimization

src/cmds/qselect.c, src/cmds/qstat.c, src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_selectj.c, src/lib/Libifl/pbsD_statque.c, src/lib/Libifl/pbsD_statsrv.c
* Fix for crash at IFL layer during aggregation
* Size doesn't display unit
* Aggregation does not show values when there is no job in the first server
* qselect issues
* Aggregation does not have to performed when invoked by sched
=> Fix for IFL crash and other bugs

src/cmds/scripts/pbs_pocker
* Support for user defined PBS_HOME
* Support for setup cluster with debug version of PBS (aka PBS compiled with -O0)
=> Add support for user defined PBS_HOME and debug version of PBS

src/cmds/scripts/pbs_pocker
=> Fix typo in pocker

src/lib/Libifl/int_status.c, src/lib/Libifl/pbsD_selectj.c
Creating parallel requests during stat as a separate PR.
CC:
@subhasisb ,
@suresh-thelkar
=> Parallel requests during stat
